"use client";

import React from "react";
import { motion } from "framer-motion";
import { Heart, Home, ShieldCheck, Clock, Phone, MapPin, Mail, CheckCircle2, CalendarCheck, Sparkles, BriefcaseBusiness, Car, Utensils, ShowerHead, ClipboardCheck, Star, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const LOGO_HORIZONTAL = "/logo-horizontal.jpg";
const LOGO_STACKED = "/logo-stacked.png";

const services = [
  { icon: Heart, title: "Companion Care", text: "Conversation, hobbies, walks, reminders, social connection, and friendly support for seniors who want to remain independent at home." },
  { icon: ShowerHead, title: "Personal Care", text: "Respectful help with bathing, dressing, grooming, toileting, mobility, and daily routines while preserving dignity and comfort." },
  { icon: Home, title: "Homemaking", text: "Light housekeeping, laundry, organization, grocery support, and help keeping the home clean, safe, and comfortable." },
  { icon: Utensils, title: "Meal Support", text: "Meal planning, simple meal preparation, hydration reminders, and help making mealtimes easier and more enjoyable." },
  { icon: ShieldCheck, title: "Memory Care Support", text: "Patient routines and supervision for individuals living with Alzheimer’s, dementia, or cognitive changes." },
  { icon: Clock, title: "Respite Care", text: "Reliable relief for family caregivers so they can rest, work, travel, or recharge with confidence." },
  { icon: CalendarCheck, title: "Transition Home Care", text: "Short-term support after a hospital stay, rehab discharge, surgery, or illness to help make coming home safer." },
  { icon: Car, title: "Errands & Transportation", text: "Help with errands, grocery trips, appointments, and everyday tasks that support independence." },
];

const steps = [
  { number: "01", title: "Free Home Care Assessment", text: "We learn about your loved one’s needs, routines, safety concerns, schedule, and family goals." },
  { number: "02", title: "Custom Care Plan", text: "Together, we create a flexible plan that fits your family, from a few hours a week to daily support." },
  { number: "03", title: "Caregiver Match", text: "We thoughtfully match care based on needs, personality, comfort level, and the support that matters most." },
];

const areas = ["Milford", "Highland", "Commerce", "White Lake", "Novi", "Wixom", "Brighton", "South Lyon", "West Bloomfield", "Oakland County"];
const faqs = [
  { q: "What kind of care do you provide?", a: "Caring Hands of Michigan provides non-medical in-home care, including companion care, personal care, homemaking, respite care, meal support, memory care support, transition-home assistance, errands, and transportation." },
  { q: "Is care flexible?", a: "Yes. Care can be scheduled around your family’s needs, including part-time visits, daily support, overnight care, temporary care after a hospital stay, or ongoing help." },
  { q: "How do we know what level of care is needed?", a: "We begin with a free consultation to understand daily routines, mobility, safety concerns, personal care needs, family preferences, and budget. From there, we recommend a custom plan." },
  { q: "Do you provide medical care?", a: "We focus on non-medical home care. Skilled nursing, wound care, therapy, and medication administration should be handled by licensed medical providers." },
];

export default function CaringHandsWebsite() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <header className="sticky top-0 z-50 border-b border-sky-100 bg-white/90 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <a href="#home" className="flex items-center gap-3"><img src={LOGO_STACKED} alt="Caring Hands of Michigan logo" className="h-11 w-auto md:hidden" /><img src={LOGO_HORIZONTAL} alt="Caring Hands of Michigan logo" className="hidden h-11 w-auto md:block" /></a>
          <nav className="hidden items-center gap-7 text-sm font-medium text-slate-700 md:flex"><a href="#services" className="hover:text-sky-600">Services</a><a href="#process" className="hover:text-sky-600">How It Works</a><a href="#about" className="hover:text-sky-600">About</a><a href="#areas" className="hover:text-sky-600">Areas</a><a href="#careers" className="hover:text-sky-600">Careers</a></nav>
          <Button className="rounded-full bg-sky-500 px-5 text-white hover:bg-sky-600" asChild><a href="#contact">Free Assessment</a></Button>
        </div>
      </header>

      <main id="home">
        <section className="relative overflow-hidden bg-gradient-to-br from-sky-950 via-sky-700 to-cyan-400 text-white">
          <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "radial-gradient(circle at 20% 20%, white 0, transparent 28%), radial-gradient(circle at 80% 10%, white 0, transparent 24%)" }} />
          <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 md:grid-cols-2 md:py-28">
            <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
              <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm font-semibold ring-1 ring-white/25"><Sparkles className="h-4 w-4" /> Compassionate care, right at home</div>
              <h1 className="max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">Helping Michigan families care for the people they love most.</h1>
              <p className="mt-6 max-w-xl text-lg leading-8 text-sky-50">Caring Hands of Michigan provides dependable, non-medical in-home care that helps seniors remain safe, comfortable, and connected in the place they know best: home.</p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" className="rounded-full bg-white px-7 text-sky-800 hover:bg-sky-50" asChild><a href="#contact">Request Free Assessment</a></Button><Button size="lg" variant="outline" className="rounded-full border-white/50 bg-transparent px-7 text-white hover:bg-white/10" asChild><a href="tel:+12485550123"><Phone className="mr-2 h-4 w-4" /> Call Now</a></Button></div>
              <div className="mt-8 grid max-w-xl grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-white/12 p-4 ring-1 ring-white/15"><p className="text-2xl font-bold">1:1</p><p className="text-xs text-sky-50">Personalized care</p></div><div className="rounded-2xl bg-white/12 p-4 ring-1 ring-white/15"><p className="text-2xl font-bold">24/7</p><p className="text-xs text-sky-50">Flexible support</p></div><div className="rounded-2xl bg-white/12 p-4 ring-1 ring-white/15"><p className="text-2xl font-bold">MI</p><p className="text-xs text-sky-50">Locally focused</p></div></div>
            </motion.div>
            <motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.6, delay: 0.1 }}><Card className="overflow-hidden rounded-[2rem] border-0 bg-white text-slate-900 shadow-2xl"><div className="relative h-72 bg-[url('https://images.unsplash.com/photo-1581579438747-104c53d7fbc4?auto=format&fit=crop&w=1200&q=80')] bg-cover bg-center"><img src={LOGO_STACKED} alt="Caring Hands of Michigan" className="absolute bottom-4 right-4 h-16 w-auto rounded-xl bg-white/85 p-2" /></div><CardContent className="p-7"><p className="text-sm font-bold uppercase tracking-[0.2em] text-sky-600">Care that feels personal</p><h2 className="mt-2 text-2xl font-bold">Support for daily life, peace of mind for the whole family.</h2><div className="mt-5 space-y-3 text-sm text-slate-700">{["Thoughtful caregiver matching", "Flexible schedules and care plans", "Companionship, personal care, respite, and more"].map((item) => <p key={item} className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-sky-500" /> {item}</p>)}</div></CardContent></Card></motion.div>
          </div>
        </section>

        <section id="services" className="mx-auto max-w-7xl px-6 py-20"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-600">Our Services</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">In-home care built around your family.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Whether your loved one needs occasional companionship or hands-on daily support, we create care that adapts to real life.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{services.map((service) => <Card key={service.title} className="rounded-3xl border-sky-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><CardContent className="p-7"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-100 text-sky-700"><service.icon className="h-6 w-6" /></div><h3 className="text-xl font-bold">{service.title}</h3><p className="mt-3 leading-7 text-slate-600">{service.text}</p></CardContent></Card>)}</div></section>

        <section id="process" className="bg-white py-20"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-600">How It Works</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Starting care should feel simple, not overwhelming.</h2><p className="mt-5 text-lg leading-8 text-slate-600">We guide families through the process with clear communication, practical recommendations, and a care plan designed around your loved one.</p></div><div className="grid gap-5">{steps.map((step) => <Card key={step.number} className="rounded-3xl border-sky-100 shadow-sm"><CardContent className="flex gap-5 p-6"><div className="text-3xl font-black text-sky-600">{step.number}</div><div><h3 className="text-xl font-bold">{step.title}</h3><p className="mt-2 leading-7 text-slate-600">{step.text}</p></div></CardContent></Card>)}</div></div></div></section>

        <section id="about" className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div className="rounded-[2rem] bg-sky-900 p-8 text-white shadow-xl"><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-100">Why Families Choose Us</p><h2 className="mt-3 text-3xl font-bold md:text-5xl">Local care with a personal touch.</h2><p className="mt-5 leading-8 text-sky-50">Caring Hands of Michigan was built for families who want dependable help without losing the warmth, respect, and trust that home care should provide. We focus on safety, dignity, consistency, and communication.</p><div className="mt-7 grid gap-3">{["Free care assessment", "Personalized care plans", "Caregiver matching", "Clear communication with families", "Flexible scheduling options"].map((item) => <p key={item} className="flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-sky-200" /> {item}</p>)}</div></div><div className="grid gap-5 sm:grid-cols-2">{[[ShieldCheck,"Dependable","Reliable support that helps seniors stay safe and families feel informed."],[Heart,"Compassionate","Care delivered with patience, respect, kindness, and dignity."],[Users,"Family-Focused","We support both the person receiving care and the loved ones coordinating it."],[Star,"Personalized","Every care plan is built around routines, preferences, and goals."]].map(([Icon,title,text]: any) => <Card key={title} className="rounded-3xl border-sky-100"><CardContent className="p-7"><Icon className="h-9 w-9 text-sky-500" /><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 text-slate-600">{text}</p></CardContent></Card>)}</div></div></section>

        <section id="areas" className="bg-sky-50 py-20"><div className="mx-auto max-w-7xl px-6 text-center"><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-600">Service Areas</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Proudly serving families across Southeast Michigan.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Based in Michigan, we support seniors and families throughout the surrounding communities.</p><div className="mx-auto mt-10 flex max-w-4xl flex-wrap justify-center gap-3">{areas.map((area) => <span key={area} className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-sky-700 shadow-sm ring-1 ring-sky-100"><MapPin className="mr-1 inline h-4 w-4" />{area}</span>)}</div></div></section>

        <section id="careers" className="bg-white py-20"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-600">Careers</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Become a Caring Hands caregiver.</h2><p className="mt-5 text-lg leading-8 text-slate-600">If you are dependable, compassionate, and passionate about helping seniors live with dignity at home, we would love to meet you.</p></div><Card className="rounded-3xl border-sky-100 bg-sky-900 text-white shadow-xl"><CardContent className="p-8"><BriefcaseBusiness className="h-10 w-10 text-sky-100" /><h3 className="mt-4 text-2xl font-bold">Now accepting caregiver applications</h3><p className="mt-3 leading-7 text-sky-50">Flexible schedules, meaningful work, and the opportunity to make a real difference for Michigan families.</p><Button className="mt-6 rounded-full bg-white text-sky-800 hover:bg-sky-50" asChild><a href="mailto:careers@caringhandsofmichigan.com">Apply Today</a></Button></CardContent></Card></div></section>

        <section id="faq" className="mx-auto max-w-5xl px-6 py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-600">FAQ</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Common questions from families.</h2></div><div className="mt-10 grid gap-4">{faqs.map((faq) => <Card key={faq.q} className="rounded-3xl border-sky-100"><CardContent className="p-6"><h3 className="text-lg font-bold">{faq.q}</h3><p className="mt-2 leading-7 text-slate-600">{faq.a}</p></CardContent></Card>)}</div></section>

        <section id="contact" className="bg-gradient-to-br from-sky-900 to-cyan-600 px-6 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-start"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-sky-100">Free Assessment</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Let’s talk about the care your family needs.</h2><p className="mt-5 text-lg leading-8 text-sky-50">Call today or complete the form and a member of our team will reach out to discuss care options, scheduling, and next steps.</p><div className="mt-8 space-y-4 text-sky-50"><p className="flex items-center gap-3"><Phone className="h-5 w-5" /> (248) 555-0123</p><p className="flex items-center gap-3"><Mail className="h-5 w-5" /> hello@caringhandsofmichigan.com</p><p className="flex items-center gap-3"><MapPin className="h-5 w-5" /> Serving Milford and surrounding Michigan communities</p></div></div><Card className="rounded-[2rem] border-0 bg-white text-slate-900 shadow-2xl"><CardContent className="p-8"><div className="mb-6 flex items-center gap-3"><ClipboardCheck className="h-8 w-8 text-sky-500" /><div><h3 className="text-2xl font-bold">Request your free home care assessment</h3><p className="text-sm text-slate-600">This form can connect to your website, CRM, or email inbox.</p></div></div><form className="grid gap-4"><input className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-sky-500" placeholder="Your name" /><input className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-sky-500" placeholder="Phone number" /><input className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-sky-500" placeholder="Email address" /><select className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-sky-500" defaultValue=""><option value="" disabled>Type of care needed</option><option>Companion care</option><option>Personal care</option><option>Respite care</option><option>Memory care support</option><option>Post-hospital / transition home care</option><option>Not sure yet</option></select><textarea className="min-h-28 rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-sky-500" placeholder="Tell us a little about your care needs" /><Button type="button" className="rounded-full bg-sky-500 py-6 text-base text-white hover:bg-sky-600">Submit Assessment Request</Button></form></CardContent></Card></div></section>
      </main>

      <footer className="bg-slate-950 px-6 py-10 text-slate-300"><div className="mx-auto flex max-w-7xl flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><img src={LOGO_STACKED} alt="Caring Hands of Michigan logo" className="h-10 w-auto rounded bg-white p-1" /><div><p className="font-bold text-white">Caring Hands of Michigan</p><p className="text-sm">Non-medical in-home care</p></div></div><p className="text-sm">© 2026 Caring Hands of Michigan. All rights reserved.</p></div></footer>
    </div>
  );
}
